name: .NET Quick Build

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:CORE_ONLY=true /p:V6_ONLY=true
    - name: Test
      run: dotnet test ./test/FlexLabs.EntityFrameworkCore.Upsert.Tests --no-build /p:V6_ONLY=true
