name: .NET Full Build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 25432:5432
        env:
          POSTGRES_DB: testuser
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: Password12!
      mysql:
        image: mysql
        ports:
          - 23306:3306
        env:
          MYSQL_DATABASE: testuser
          MYSQL_USER: testuser
          MYSQL_ROOT_PASSWORD: Password12!
          MYSQL_PASSWORD: Password12!
      mssql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 21433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:CORE_ONLY=true /p:V6_ONLY=true
    - name: Test
      run: dotnet test --no-build /p:V6_ONLY=true

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - uses: actions/checkout@v2
    - name: Enable Postgres
      run: sc config postgresql-x64-14 start= demand
    - name: Start Postgres
      run: net start postgresql-x64-14
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:POSTGRES_ONLY=true /p:V6_ONLY=true
    - name: Test
      run: dotnet test --no-build /p:V6_ONLY=true
