name: Release API client nuget

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/monfex"

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.*
          8.0.*
        source-url: https://nuget.pkg.github.com/myjetwallet/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}  

    - name: list nugets
      run: dotnet nuget list source
      
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${{ inputs.release_version }}

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Create the package
      run: dotnet pack --configuration Release src/FlexLabs.EntityFrameworkCore.Upsert /p:Version=${{ inputs.release_version }}

    - name: Publish the package to GPR
      run: dotnet nuget push src/FlexLabs.EntityFrameworkCore.Upsert/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}

    - name: Publish the package to GitHub
      uses: MyJetWallet/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  './src/FlexLabs.EntityFrameworkCore.Upsert/bin/Release/*.nupkg'
        repo-owner:  'myjetwallet'
        gh-user:  ${{ github.actor }}
        token:  ${{ secrets.NUGET_AUTH_TOKEN }}
